Add 3 more controllers and serializers for that models.
MurkyMeow/lecture pull request #18
Opened 2019-09-22 16:52 UTC by pCoLDq

Fix: #16

2019-09-23 20:36 UTC, MurkyMeow commented on MainApp/urls.py
> +    path('get_slides/', GetSlides),
Все маршруты называются существительными, эти &mdash; почему-то глаголами =).

2019-09-23 20:46 UTC, MurkyMeow commented on MainApp/views.py
> +    serializer = LectureSerializer(Lecture.objects.filter(course=course) ,many=True)
Хм, ты уверен, что это хороший способ получать зависимые объекты?

Я думаю, это должно быть определено на уровне самого сериализатора. Посмотри первый пример тут:

https://www.django-rest-framework.org/api-guide/relations/#nested-relationships

2019-09-23 20:48 UTC, MurkyMeow requested changes
Будет здорово, если ты ещё добавишь тесты. Спасибо!

2019-09-28 08:12 UTC, pCoLDq commented on MainApp/views.py
> +    serializer = LectureSerializer(Lecture.objects.filter(course=course) ,many=True)
Зачем усложнять, если можно не усложнять?

2019-09-28 22:37 UTC, MurkyMeow commented on MainApp/views.py
> +    serializer = LectureSerializer(Lecture.objects.filter(course=course) ,many=True)
Упс, я, видимо, не туда оставила комментарий.

Пример по ссылке должен упростить код отсюда (посмотри на него, пожалуйста):

https://github.com/MurkyMeow/lecture/pull/17/files#diff-f69f3f47634def5e6fa6571afe1a1f2cR40

Если говорить о данном коде, то он совершает _лишний_ запрос к бд, запрашивая курс. Вместо этого в filter в поле course можно напрямую передать число:

```python
lectures = Lecture.objects.filter(course=request.GET.get('course_id'))
```

Или, для пущей ясности, использовать course_id:

```python
lectures = Lecture.objects.filter(course_id=request.GET.get('course_id'))
```

2019-09-28 22:41 UTC, MurkyMeow commented on MainApp/views.py
> +    serializer = SlideSerializer(Slide.objects.filter(lecture=lecture) ,many=True)
И не забудь про этот случай.

2019-09-29 06:27 UTC, pCoLDq commented on MainApp/views.py
> +    serializer = LectureSerializer(Lecture.objects.filter(course=course) ,many=True)
Разве мы не проходили, что в foreign key нужно передавать экземпляр, а не id?

2019-09-29 06:34 UTC, pCoLDq commented on MainApp/views.py
> +    serializer = LectureSerializer(Lecture.objects.filter(course=course) ,many=True)
Я имею в виду, что у нас уже была ошибка, когда мы передавали id вместо объекта, и тогда пришли к умозаключению, что id это лишь реализация самого класса Foreign key.

2019-09-29 06:34 UTC, pCoLDq commented on MainApp/views.py
> +    serializer = LectureSerializer(Lecture.objects.filter(course=course) ,many=True)
23 августа, в лс вк.

2019-10-01 23:53 UTC, MurkyMeow approved these changes

2019-10-01 23:54 UTC, merged